// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmL9xG0n7ihGBreJHF0d2OtD9cDyWW5Q',
    appId: '1:983602238281:web:3993682950ab7b31870098',
    messagingSenderId: '983602238281',
    projectId: 'peekblocknew',
    authDomain: 'peekblocknew.firebaseapp.com',
    storageBucket: 'peekblocknew.firebasestorage.app',
    measurementId: 'G-XMCL21SDQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8G7iXaqAo6U_n1bwOW-qDfmS06pN-l-U',
    appId: '1:983602238281:android:019dce845956fbb4870098',
    messagingSenderId: '983602238281',
    projectId: 'peekblocknew',
    storageBucket: 'peekblocknew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntnUXj4D0W2kvKGEvOFKMoB3zt0YiIdM',
    appId: '1:983602238281:ios:314292adf95472f0870098',
    messagingSenderId: '983602238281',
    projectId: 'peekblocknew',
    storageBucket: 'peekblocknew.firebasestorage.app',
    iosBundleId: 'com.example.peekblockNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntnUXj4D0W2kvKGEvOFKMoB3zt0YiIdM',
    appId: '1:983602238281:ios:314292adf95472f0870098',
    messagingSenderId: '983602238281',
    projectId: 'peekblocknew',
    storageBucket: 'peekblocknew.firebasestorage.app',
    iosBundleId: 'com.example.peekblockNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBmL9xG0n7ihGBreJHF0d2OtD9cDyWW5Q',
    appId: '1:983602238281:web:64723acca2c5ce6f870098',
    messagingSenderId: '983602238281',
    projectId: 'peekblocknew',
    authDomain: 'peekblocknew.firebaseapp.com',
    storageBucket: 'peekblocknew.firebasestorage.app',
    measurementId: 'G-B16KKT18TJ',
  );
}
